name: egwolfe
favicon: null
layout_spectrum: 1
typography_spectrum: 0.72634
title: egwolfe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d9fc7'
    - '#27221e'
    - '#455a73'
    - '#dadee7'
    - '#767f45'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
