name: egwolfe
favicon: null
layout_spectrum: 0.28515881299972534
typography_spectrum: 0.8188318447209895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6689271118957549
  lightness: 0.2507417711894959
  saturation: 0.6638916782103479
  rhythmicContrast: 0.4289643408264965
purpose: []
