title: egwolfe
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.9974705
  brandStrength: 0.8364662
  lightness: 0.08646616
  brandColors:
    - '#88AAD0'
    - '#6687B0'
    - '#37455F'
    - '#A5959A'
    - '#C4A9A2'
  rhythmicContrast: 0.508772
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: egwolfe
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.806391
layout_spectrum: 1
